import httpx
from typing import Optional
from app.core.config import settings

async def call_gemini(prompt: str, system_instruction: Optional[str] = None) -> str:
    # 1. Try Groq first if key is present
    groq_key = settings.GROQ_API_KEY
    if groq_key:
        url = "https://api.groq.com/openai/v1/chat/completions"
        headers = {
            "Authorization": f"Bearer {groq_key}",
            "Content-Type": "application/json"
        }
        messages = []
        if system_instruction:
            messages.append({"role": "system", "content": system_instruction})
        messages.append({"role": "user", "content": prompt})
        
        payload = {
            "model": "llama-3.3-70b-versatile",
            "messages": messages,
            "temperature": 0.2
        }
        
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(url, headers=headers, json=payload, timeout=30.0)
                
            if response.status_code != 200:
                return f"Groq API Error (HTTP {response.status_code}): {response.text}"
                
            res_data = response.json()
            choices = res_data.get("choices", [])
            if not choices:
                return "No response generated by Groq."
                
            message = choices[0].get("message", {})
            return message.get("content", "")
            
        except httpx.RequestError as exc:
            return f"Groq request failed: {str(exc)}"

    # 2. Fallback to Gemini if GROQ_API_KEY is not configured
    api_key = settings.GEMINI_API_KEY
    if not api_key:
        return "AI API keys are not configured. Please set the GROQ_API_KEY or GEMINI_API_KEY environment variable."

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
    
    payload = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ]
    }
    
    if system_instruction:
        payload["systemInstruction"] = {
            "parts": [
                {"text": system_instruction}
            ]
        }

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(url, json=payload, timeout=30.0)
            
        if response.status_code != 200:
            return f"Gemini API Error (HTTP {response.status_code}): {response.text}"
            
        res_data = response.json()
        candidates = res_data.get("candidates", [])
        if not candidates:
            return "No response generated by Gemini."
            
        content = candidates[0].get("content", {})
        parts = content.get("parts", [])
        if not parts:
            return "Empty content generated by Gemini."
            
        return parts[0].get("text", "")
        
    except httpx.RequestError as exc:
        return f"Gemini request failed: {str(exc)}"
